### ISSUE TITLE
Trigger a new build

### ISSUE THREAD

**Issue by pchampio** [efrecon/docker-s3fs-client#10]
A  new version is available in https://github.com/s3fs-fuse/s3fs-fuse/releases/tag/v1.89
but not available in https://hub.docker.com/r/efrecon/s3fs/tags?page=1&ordering=last_updated

**Comment by efrecon** [comment]
I have triggered a new build. Ping me back if it does not pick up the new version.

**Comment by pchampio** [comment]
Ping ;)
https://hub.docker.com/r/efrecon/s3fs/tags?page=1&ordering=last_updated

**Comment by efrecon** [comment]
I had arranged for this to be built automatically when a new release was made. Unfortunately, automatic builds are gone from the free Docker Hub tier. I am slowly migrating my projects to using GitHub actions instead. Expect this to happen for the s3fs image soon.

**Comment by efrecon** [comment]
It is there now @pchampio. I have migrated to using workflows.
