### ISSUE TITLE
s3fs: unable to access MOUNTPOINT {bucketname}: No such file or directory

### ISSUE THREAD

**Issue by torblerone** [efrecon/docker-s3fs-client#11]
Greetings,

I've tried your container with latest version of `s3fs` running on `1.89`.

When I try to setup the container using a MinIO backend endpoint, I run into the following error:

```
s3fs: Unable to access MOUNTPOINT my-bucket: No such file or directory
Mount failure
```

I guess your startup script created the directory `/opt/s3fs/bucket` but not the directory which actually holds the bucket, which would need to be `opt/s3fs/bucket/my-bucket` if I understand correctly.

Thus, you'd have to change the entrypoint script to `mkdir -p $DEST/$AWS_S3_BUCKET` or something like that.

I used `ACCESS_KEY`/`SECRET_KEY` combination instead of a keyfile and added `S3FS_ARGS: "use_path_request_style,allow_other,default_acl=public"`.

Do you have any other hints on this?

**Comment by torblerone** [comment]
News:

I seemed to have solved the problem myself. For everyone hitting this problem, this might be the solution:

`S3FS_ARGS` is handed over as-is, thus it may not have the `s3fs`'ish needed `-o` flag.

Instead of setting `S3FS_ARGS="use_path_request_style,..."`, you'd rather set it `S3FS_ARGS="-o use_path_request_style"`.

Maybe this should be changed in the `docker-entrypoint.sh` script so it won't lead to confusion.

**Comment by efrecon** [comment]
I merged your PR as it provides a better alternative. Closing this now, thank you again.

**Comment by bhuiyanmobasshir94** [comment]
Finding this issue `s3fs: unable to access MOUNTPOINT /faceid_bucket: No such file or directory`
