### ISSUE TITLE
GID must be specified when UID is specified

### ISSUE THREAD

**Issue by totycro** [efrecon/docker-s3fs-client#2]
Hi!

Thanks for providing this very convenient docker image!

I just noticed a minor issue: If you specify the UID, but not the GID, then the mount actually fails.
The first problem is here, where adduser fails due to GID being 0, so you get  `adduser: unknown group 0`:
https://github.com/efrecon/docker-s3fs-client/blob/master/docker-entrypoint.sh#L48

Therefore the user is not created and the subsequent commands fail.

This is not really a bug, but it might be nice to e.g. get a more precise error message or set GID to some default value.

**Comment by efrecon** [comment]
You fixed it, it's merged! So I close this. Thanks again.
