### ISSUE TITLE
Update latest docker image

### ISSUE THREAD

**Issue by regbo** [efrecon/docker-s3fs-client#21]
It took me a long time to realize that even though this issue is solved:

https://github.com/efrecon/docker-s3fs-client/issues/11

It's not solved in the latest docker image. You should push an update when you can or make a note.

**Comment by efrecon** [comment]
This should be fixed as soon as this [run](https://github.com/efrecon/docker-s3fs-client/runs/5235555141) has finished.

**Comment by gmeligio** [comment]
For some reason, the latest docker tag was pushed [2 years ago](https://hub.docker.com/layers/s3fs/efrecon/s3fs/latest/images/sha256-56c87521168d51da8bd81a6ecbfa5097c30c839fa449858724cbca7a15fea926?context=explore) and doesn't have the latest changes. It took me one day to understand why the configuration wasn't working. There should be something missing in the Github workflow.

Using `efrecon/s3fs:1.91` fixed it for me.

**Comment by efrecon** [comment]
No, this is actually more or less on purpose, as the idea is for the images to follow the release process for s3fs. I understand that this might be puzzling, so I have updated the README and removed the (very old) `latest` image that was still lying around at the DockerHub.

**Comment by gmeligio** [comment]
Thank you. Really good work! It's good to follow `s3fs` versioning.
