### ISSUE TITLE
How to add mount to another container

### ISSUE THREAD

**Issue by tobyworks** [efrecon/docker-s3fs-client#27]
Right now i have sucesfully running this docker container. to expose my wasabi (s3) bucket. I would like to use it in my plex container. But i cant use the /mnt/ that i have defined in the plex container.

**Comment by efrecon** [comment]
hmmm. I am a bit unsure I understand your exact problem but here is what I think you should do.

1. Arrange for a directory to exist on the Docker host, e.g. `/mnt/wasabi`
2. Create a container using this image to mount your wasabi bucket
3. Create another container for plex mounting `/mnt/wasabi` onto something relevant for plex.

Does it make sense?

**Comment by efrecon** [comment]
I am closing this. As I assume you've fixed it. For the record, adding the `:rshared` to the volume mount specification is usually key to what I *think* your problem was.
