### ISSUE TITLE
Running container with command docker service

### ISSUE THREAD

**Issue by efenfauzi** [efrecon/docker-s3fs-client#30]
From docs say its posible running on swarm enviroment. I have 2 node with active swarm joined. Simplest trial is running container service with `docker service create --env bla blah blah --constraint node` 

And i still confuse from file `docker-compose.yml` with : 

 ```
    security_opt:
          - 'apparmor:unconfined'
    devices:
          - /dev/fuse
 ```
      
      
this no option when run with docker container. 
My plan just simple, I want to try this s3 container service on swarm mode.  
Example :
- container on node 1 backup log file
- container s3 on node 2 accept backup log file from mount

**Comment by efrecon** [comment]
It's been a while I dabbled with swarm, but have a look here: https://serverfault.com/questions/824516/how-to-set-linux-capabilities-on-docker-swarm-mode-service-invocations there is a solution to run a container directly on the host in the comments.

**Comment by efrecon** [comment]
@efenfauzi Did you solve this? [`security_opt`](https://docs.docker.com/compose/compose-file/#security_opt) seems to be part of the latest spec, as is [`devices`](https://docs.docker.com/compose/compose-file/#devices). Don't they work with `docker stack deploy`?

**Comment by efrecon** [comment]
Closing this in lack of response
