### ISSUE TITLE
Mounted volume is empty

### ISSUE THREAD

**Issue by korsar182** [efrecon/docker-s3fs-client#31]
Hi,
I'm running docker-compose file from the repo, everything works fine, I can see bucket files inside container, but mounted host directory is empty. What's wrong with that?

**Comment by efrecon** [comment]
You likely have forgotten to add `:rshared` to the `-v` option (or equivalent in the compose file). I am closing this, but feel free to reopen in case this wasn't it.

**Comment by nrukavkov** [comment]
@efrecon does exist some workaround for mac os? There is no rshared in mac https://github.com/docker/for-mac/issues/3431
