### ISSUE TITLE
fuse: unknown option `endpoint="ap_east_1"'

### ISSUE THREAD

**Issue by kkmehta03** [efrecon/docker-s3fs-client#35]
Hello, 

I'm getting this issue when I add `S3FS_ARGS= endpoint=\"ap-east-1\"` in my .env file. 
Unsure what I'm doing wrong. 
Can you help? 

Thanks!

**Comment by gaul** [comment]
Try `S3FS_ARGS="-o endpoint=ap-east-1"`.
