### ISSUE TITLE
Session Token

### ISSUE THREAD

**Issue by tranzmatt** [efrecon/docker-s3fs-client#39]
Does this support session tokens?  I have a bucket that requires a session token and can do it from the CLI with s3fs, but adding the variable to the docker-compose or calling it from the command line didn't seem to do anything.

**Comment by efrecon** [comment]
It should if you:

+ add `use_session_token` to the `S3FS_ARGS` variable
+ Point to a credentials file using the `AWS_S3_AUTHFILE` variable

**Comment by efrecon** [comment]
Closing. Proposed solution should work (cannot verify)
