### ISSUE TITLE
[HCP] Hitachi Content Platform

### ISSUE THREAD

**Issue by gray380** [efrecon/docker-s3fs-client#40]
Hello,

I can mount HCP's s3 bucket on the host from the `cli`:
```
s3fs bucket-test /mnt/bucket-test -o passwd_file=${HOME}/.passwd -o url=https://test.s3-hcp.lan/ -o use_path_request_style
```
`${HOME}/.passwd` contains `<key-id>:<access-key>`

but when I try to mount the bucket within docker:
```
docker run -it --rm \
    --device /dev/fuse \
    --cap-add SYS_ADMIN \
    --security-opt "apparmor=unconfined" \
    --env "AWS_S3_BUCKET=bucket-test" \
    --env "AWS_S3_ACCESS_KEY_ID=<key-id>" \
    --env "AWS_S3_SECRET_ACCESS_KEY=<access-key>" \
    --env "AWS_S3_URL=https://video.s3-hcp.bank.lan/" \
    --env "S3FS_ARGS=use_path_request_style" \
    --env UID=$(id -u) \
    --env GID=$(id -g) \
    -v /mnt/bucket-test:/opt/s3fs/bucket:rshared \
    efrecon/s3fs:1.91
    ```
the following error has appeared:
```
ls: /opt/s3fs/bucket: Connection aborted
```

Could you help me to find out the abortion cause?

brg
Serhiy.

**Comment by efrecon** [comment]
I don't have access to the HCP, but you could have been a victim of #41. Can you try again as soon as this [job](https://github.com/efrecon/docker-s3fs-client/actions/runs/4085734002/jobs/7044097443) has finished. 
Can you try setting up debugging if that helps?  (use the `S3FS_DEBUG` environment variable).

**Comment by efrecon** [comment]
Closing this now, as a long (silent) time has passed.
