### ISSUE TITLE
s3fs: unable to access MOUNTPOINT {bucketname}: No such file or directory

### ISSUE THREAD

**Issue by haytham-mostafa** [efrecon/docker-s3fs-client#45]
Hey,

I am trying to mount S3 sub-directories, using the following command:
`s3fs -o iam_role="mediation-ocomc-lit" -o url="https://s3-eu-central-1.amazonaws.com" -o endpoint=eu-central-1 -o dbglevel=info -o curldbg -o allow_other -o use_cache=/tmp mp_umask=002 -o multireq_max=5  iotbigdatarawfilesft-lit:/InputFiles/OCOMC-mnt/ /opt/SP/users/oracle/data/input/  `

but I am stuck now with this error:
`s3fs: unable to access MOUNTPOINT iotbigdatarawfilesft-lit:/InputFiles/OCOMC-mnt/: No such file or directory`

I have tried a lot of fixes but with no success, actually I don't know what's the issue.
Please advise

Thanks & BR,
Haytham

**Comment by efrecon** [comment]
You seem to have forgotten the `-o` in front of the `mp_umask=002` option setting. **BUT** to pass additional options, you should set the `S3FS_ARGS` environment variable with a **comma** separated list of (additional) options to be set, e.g. `iam_role=mediation-ocomc-lit,endpoint=eu-central-1,dbglevel=info,...`

Also note that I did remove the URL from the example above, as you should use the `AWS_S3_URL`.

This is all described in the [README](https://github.com/efrecon/docker-s3fs-client/tree/master#container-options)

**Comment by efrecon** [comment]
Reopened because I also figured out that you've probably misunderstood the purpose of this image. It does **not** work with Docker volumes, e.g. your `iotbigdatarawfilesft-lit:`. Instead you have to "book" yourself a directory on the host where to mount stuff. I *guess* you might be able to provide the entire path to an existing volume on the host, but I've never tried that.

**Comment by haytham-mostafa** [comment]
it's not a Docker volumes indeed, I am trying to mount S3 bucket path to an EC2 instance
