### ISSUE TITLE
Add arm64 arch. build to DockerHub releases

### ISSUE THREAD

**Issue by tab10** [efrecon/docker-s3fs-client#46]
Just a suggestion: could you add a arm64 architecture build when you do releases on the Dockerhub? This is becoming more popular on AWS instances and for the Apple M1 chip. 

Specifying `platform: linux/arm64` for this container in the Dockerfile/Compose file will cause the build to fail for me in 1.92. A standard x86_64 arch. set like  `platform: linux/amd64` builds normally. Thank you.

https://hub.docker.com/r/efrecon/s3fs

**Comment by efrecon** [comment]
1.93 has an arm64 build at the [GHCR](https://github.com/efrecon/docker-s3fs-client/pkgs/container/s3fs/116567619?tag=1.93) and the [hub](https://hub.docker.com/layers/efrecon/s3fs/1.91/images/sha256-05f616a44d411830e213829c64d10cb474624219becbf7ebeb305137c09e3339?context=explore). Don't they work?

**Comment by efrecon** [comment]
Closing since there are now ARM versions
