### ISSUE TITLE
is --volumes-from a possibility?

### ISSUE THREAD

**Issue by juaoose** [efrecon/docker-s3fs-client#47]
I tried using `docker run --volumes-from <s3fs-container-id>` and the base directory is available, but then the bucket content is not there. Is this because of the lack of `rshared` bind propagation? Is there any way to do something like mounting from another container without having to mount on the host?

Thanks!

**Comment by efrecon** [comment]
I don't think I have ever tried. But since volumes and volumes of
containers are an abstraction for directories on the host, I would believe
you need the rshared abstraction.

Den fre 15 sep. 2023 05:19Juan R ***@***.***> skrev:
