### ISSUE TITLE
COPY failed: no source files were specified  

### ISSUE THREAD

**Issue by Zonalds** [efrecon/docker-s3fs-client#6]
Hey,

Thanks for providing this. While trying to build the image with the provided Dockerfile, I would get this error:

`Step 13/23 : COPY *.sh /usr/local/bin/                                                                             
COPY failed: no source files were specified  `

Any idea how to fix this?

**Comment by efrecon** [comment]
I have `24` steps when I run (being lazy, no tag for the sake of the test):

```shell
docker build .
```

The `COPY` step works as it should. @Zonalds are you sure you were running the `build` command from the main directory of the repository?
