### ISSUE TITLE
How can i set  UID and GID differ than su RUNAS user? 

### ISSUE THREAD

**Issue by rolsite** [efrecon/docker-s3fs-client#9]
Hi,

My apache user is www:data (UID 33 AND GID 33)

su RUNAS command only work with  UID 1000 and GID 1000.

How can i set  UID and GID differ than su RUNAS user?

**Comment by efrecon** [comment]
Have you tried setting the environment variables `UID` and `GID` to 33 when running?

**Comment by efrecon** [comment]
This is old and has become stale. I will close with a final thought. Maybe should migrate the ideas from [this](https://github.com/jmccormick2001/rqlite-operator/tree/master/build) implementation.
